# 国ごとの設定。基準（絞り込み・縮尺・色）は共通で、ここに書くのは国の違いだけ。
import os

TOOL = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.normpath(os.path.join(TOOL, '..', '..'))          # Academic-Gate_hp/
# 取ってきたデータ（.osm.pbf・Natural Earth・途中の GeoJSON）の置き場。リポジトリには入れない（.gitignore）。
DATA = os.environ.get('MVCARDS_DATA', os.path.join(TOOL, 'data'))
NE = os.path.join(DATA, 'ne')
SVG_DIR = os.path.join(SITE, 'image', 'memoryverse', 'cards')    # 生成物：SVG
PAGE_DIR = os.path.join(SITE, 'html', 'country')                 # 生成物：国のページ

COUNTRIES = {
    'JPN': {
        'dir': os.path.join(DATA, 'JPN'),
        'terms': '<b>区分の呼び名</b>：この国の区分は<b>都道府県</b>（47）。地図の名前がそのまま現地の呼び名で、ほかの国のページと違い、日本語が原語。', 'terms_reading': False,
        'name': '日本',
        'description': '日本の国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（都道府県・地方・都市）の3層を重ねた地図。メモリーバース 3章。',
        'geofabrik': 'asia/japan-latest.osm.pbf',
        'phi0': 36.63,          # 本土（本州）の重心。領土の全体では 37.43（§100.10）
        'panels': {
            'main':   {'lon': (128.2, 146.6), 'lat': (29.9, 46.2), 'title': '本土'},
            'ryukyu': {'lon': (122.4, 130.4), 'lat': (23.6, 30.4), 'title': '南西諸島（本土と同じ縮尺）'},
        },
        # Natural Earth の region を日本語に。沖縄は Natural Earth どおり独立した地方（9地方）
        'regions': {'Hokkaido': '北海道', 'Tohoku': '東北', 'Kanto': '関東', 'Chubu': '中部', 'Kinki': '近畿',
                    'Chugoku': '中国', 'Shikoku': '四国', 'Kyushu': '九州', 'Okinawa': '沖縄'},
        # データの欠けを埋める（区分は変えない）：佐賀県・長崎県は region が空
        'region_fill': {'佐賀県': 'Kyushu', '長崎県': 'Kyushu'},
        'admin1_word': '都道府県',
        'city_strip': r'[都市]$',
        'notes': [
            '図の外にある島：<b>南鳥島</b>（北緯24.3度・東経154.0度）、<b>沖ノ鳥島</b>（北緯20.4度・東経136.1度）。どちらも2枚の図の範囲より外にある。',
            'この地図の国境は、2-1 で決めたとおり実効支配で描いています。北方領土（実効支配はロシア、日本が主張）と竹島（実効支配は韓国、日本が主張）は日本の範囲に含めていないので、そこでは層2の川や道路も描かれません。日本の地図帳とは描き方が異なります。尖閣諸島（日本が実効支配）は日本の側ですが、この縮尺では1〜2pxの点です。',
        ],
        'src13': '国境・海岸線・47都道府県・9地方（佐賀県・長崎県は地方の値が無いため九州として補った）・都市（人口 POP_MAX の多い順に20）',
        'fig': '本土は東経128.2〜146.6度・北緯29.9〜46.2度、南西諸島は東経122.4〜130.4度・北緯23.6〜30.4度',
    },
    'TCD': {
        'dir': os.path.join(DATA, 'TCD'),
        'terms': '<b>区分の呼び名</b>：Natural Earth では、22の区分が <b>Préfecture</b>（プレフェクテュール）とあり、アラビア語の名前は <b dir="rtl">إقليم</b>（イクリーム）で始まる。いまの公式の呼び名かは確かめていない。', 'terms_reading': True,
        'name': 'チャド',
        'description': 'チャドの国のページ。位置と形・骨組み（川・湖・道路）・区画（州・都市）の3層を重ねた地図。メモリーバース 3章。',
        'geofabrik': 'africa/chad-latest.osm.pbf',
        'phi0': 15.28,          # 1つのかたまりなので領土の全体と同じ
        'panels': {
            'main': {'lon': (12.9, 24.5), 'lat': (6.9, 24.0), 'title': 'チャド全土'},
        },
        'regions': {},
        'region_fill': {},
        'admin1_word': '州',
        'city_strip': None,
        'notes': [],
        'src13': '国境・22州・都市（人口 POP_MAX の多い順に20。Natural Earth にチャドの都市は19しか無い）。州をまとめる地方の区分は Natural Earth に無い',
        'fig': '東経12.9〜24.5度・北緯6.9〜24.0度',
    },
}

# ---- 3-1 西ヨーロッパの9か国（本土の重心の経度で東経0度から東回り）----
# 倍率（zoom）：1度44pxのままでは図にならない国だけ上げる（§100.11）。
#   1) 上げるのは、1度44pxで図の長いほうの辺が 100px 未満になる国だけ（ルクセンブルク32・リヒテンシュタイン9・モナコ2px）。
#      ベルギー（126px）・オランダ（145px）・スイス（157px）は小さいが形は読めるので、地域のカードと同じ縮尺のまま
#   2) 倍率は、長いほうの辺が 300〜700px に収まる、10・20・50・100・200倍のうちいちばん小さいもの
#   上げた国は、図とカードの注記に「この図だけ○倍」と書く。
W31 = dict(up_href='memoryverse_3-1.html', up_label='3-1 西ヨーロッパ')
FR_REG = {'Hauts-de-France': 'オー＝ド＝フランス', 'Grand Est': 'グラン・テスト', "Provence-Alpes-Côte-d'Azur": 'プロヴァンス＝アルプ＝コート・ダジュール',
          'Auvergne-Rhône-Alpes': 'オーヴェルニュ＝ローヌ＝アルプ', 'Nouvelle-Aquitaine': 'ヌーヴェル＝アキテーヌ', 'Occitanie': 'オクシタニー',
          'Bourgogne-Franche-Comté': 'ブルゴーニュ＝フランシュ＝コンテ', 'Pays de la Loire': 'ペイ・ド・ラ・ロワール', 'Bretagne': 'ブルターニュ',
          'Normandie': 'ノルマンディー', 'Île-de-France': 'イル＝ド＝フランス', 'Centre-Val de Loire': 'サントル＝ヴァル・ド・ロワール', 'Corse': 'コルス',
          'Guyane française': '仏領ギアナ', 'Martinique': 'マルティニーク', 'Guadeloupe': 'グアドループ', 'Réunion': 'レユニオン', 'Mayotte': 'マヨット'}
COUNTRIES.update({
    'FRA': dict(W31, dir=os.path.join(DATA, 'FRA'),
        terms='<b>区分の呼び名</b>：この国の区分は <b>département</b>（デパルトマン）と呼ばれ、本土に96、海外に5ある。本土の96は13のまとまりに分かれる（Natural Earth に region として入っている。層3の「地域圏」）。', terms_reading=True, name='フランス', geofabrik='europe/france-latest.osm.pbf', phi0=46.57,
        description='フランスの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（県・地域圏・都市）の3層を重ねた地図。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (-5.5, 9.9), 'lat': (41.0, 51.4), 'title': '本土とコルシカ島'}},
        regions=FR_REG, region_fill={}, region_word='地域圏', region_suffix='', region_fs=11, region_ls=1,
        admin1_word='県', city_strip=None,
        notes=['図の外にある海外県（Natural Earth でフランスの形に含まれる5つ）：<b>仏領ギアナ</b>（北緯3.9度・西経53.0度）、<b>グアドループ</b>（北緯16.2度・西経61.6度）、<b>マルティニーク</b>（北緯14.6度・西経61.0度）、<b>レユニオン</b>（南緯21.1度・東経55.5度）、<b>マヨット</b>（南緯12.8度・東経45.1度）。埋める加工はしない。ニューカレドニアや仏領ポリネシアなどは Natural Earth では別の単位で、この図には入れていない。'],
        src13='国境・海岸線・96県（本土）と5つの海外県・地域圏・都市（人口 POP_MAX の多い順に20）',
        fig='東経−5.5〜9.9度・北緯41.0〜51.4度（本土とコルシカ島）'),
    'BEL': dict(W31, dir=os.path.join(DATA, 'BEL'),
        terms='<b>区分の呼び名</b>：10の <b>provincie</b>（オランダ語、プロヴィンシー）／<b>province</b>（フランス語、プロヴァンス）と、首都の <b>Hoofdstedelijk Gewest</b>（オランダ語）／<b>Région Capitale</b>（フランス語）。<b>どの言葉で呼ぶかは地域で違う</b>——フランデレンの5州はオランダ語、ワロンの5州はフランス語、ブリュッセルは両方。', terms_reading=True, name='ベルギー', geofabrik='europe/belgium-latest.osm.pbf', phi0=50.64,
        description='ベルギーの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（州・地域・都市）の3層を重ねた地図。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (2.2, 6.7), 'lat': (49.2, 51.8), 'title': 'ベルギー全土'}},
        regions={'Flemish': 'フランデレン', 'Walloon': 'ワロン', 'Capital Region': 'ブリュッセル首都圏'}, region_fill={},
        region_word='地域', region_suffix='地域', region_fs=13, region_ls=2, admin1_word='州', city_strip=None, notes=[],
        src13='国境・10州とブリュッセル首都圏地域・3つの地域（フランデレン・ワロン・ブリュッセル首都圏）・都市（人口 POP_MAX の多い順に20。Natural Earth にベルギーの都市は10しか無い）',
        fig='東経2.2〜6.7度・北緯49.2〜51.8度'),
    'NLD': dict(W31, dir=os.path.join(DATA, 'NLD'),
        terms='<b>区分の呼び名</b>：12の <b>Provincie</b>（プロヴィンシー）と、カリブ海の3つの <b>Bijzondere Gemeenten</b>（ビゾンデレ・ヘメーンテン、特別自治体）。', terms_reading=True, name='オランダ', geofabrik='europe/netherlands-latest.osm.pbf', phi0=52.28,
        description='オランダの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（州・都市）の3層を重ねた地図。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (3.0, 7.5), 'lat': (50.5, 53.8), 'title': '本土（ヨーロッパの部分）'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None,
        notes=['図の外にあるカリブ海の特別自治体（Natural Earth でオランダの形に含まれる3つ）：<b>ボネール</b>（北緯12.2度・西経68.2度）、<b>シント・ユースタティウス</b>（北緯17.5度・西経63.0度）、<b>サバ</b>（北緯17.6度・西経63.2度）。埋める加工はしない。アルバ・キュラソー・シント・マールテンはオランダ王国の中の別の構成国で、Natural Earth でも別の単位。',
               '首都はアムステルダム（憲法第32条）、政府と議会はハーグにある（3-1 §05）。'],
        src13='国境・12州とカリブ海の3つの特別自治体・都市（人口 POP_MAX の多い順に20。Natural Earth にオランダの都市は14しか無い）',
        fig='東経3.0〜7.5度・北緯50.5〜53.8度（ヨーロッパの部分）'),
    'LUX': dict(W31, dir=os.path.join(DATA, 'LUX'),
        terms='<b>区分の呼び名</b>：地図の3つの区分は <b>District</b>（ディストリクト）と呼ばれていた（2015年に廃止。上の注記）。ルクセンブルク語の呼び名は Natural Earth に入っていない。', terms_reading=True, name='ルクセンブルク', geofabrik='europe/luxembourg-latest.osm.pbf', phi0=49.77,
        zoom=10, fine=0.2, zoom_why='幅約22px',
        rivers_outside_note=('Our（ウール川）は国境の川で（OpenStreetMap の国境の線に沿って流れる。52.5km のうち48.8km）、国の外にあるわけではない。'
                             '<b>Natural Earth の粗い国境の線の外側に入るため、この図には描いていない。</b>Prüm（プリュム川）はドイツ側を流れる川で'
                             '（国境の線に沿うのは0.2km）、国の外にある。同じ東の国境の川でも、Mosel（モーゼル川）と Sauer（ザウアー川）は国の中に一部が入るので描いている。'),
        description='ルクセンブルクの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画・都市の3層を重ねた地図（この国の図だけ10倍）。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (5.6, 6.62), 'lat': (49.36, 50.26), 'title': 'ルクセンブルク全土'}},
        regions={}, region_fill={}, admin1_word='区', city_strip=None,
        notes=['層3の3つの「区」（ルクセンブルク・ディーキルヒ・グレーヴェンマハ）は、<b>2015年10月3日に廃止された区分</b>です。Natural Earth v5.1.2 がこの区分のままなので、直さずに描いています。いまは国と100の基礎自治体（コミューン）のあいだに行政の段がありません。'],
        src13='国境・3つの区（2015年に廃止された区分。Natural Earth のまま）・都市（人口 POP_MAX の多い順に20。Natural Earth にルクセンブルクの都市は3しか無い）',
        fig='東経5.6〜6.62度・北緯49.36〜50.26度'),
    'MCO': dict(W31, dir=os.path.join(DATA, 'MCO'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない。', terms_reading=False, name='モナコ', geofabrik='europe/monaco-latest.osm.pbf', phi0=43.74,
        zoom=200, fine=0.01, zoom_why='約1px の点',
        description='モナコの国のページ。位置と形・骨組み・区画の3層を重ねた地図（この国の図だけ200倍）。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (7.355, 7.449), 'lat': (43.71, 43.772), 'title': 'モナコ全土'}},
        regions={}, region_fill={}, admin1_word='区', city_strip=None,
        notes=['国境と海岸線は Natural Earth（1:1000万）の形で、モナコは12の点で描かれています。200倍に広げると角ばって見えるのはそのためです（層2の OSM の線はもっと細かい）。',
               '<b>Natural Earth の輪郭は19km² で、実際の約2km² より大きい</b>（12の点の多角形が海の側に張り出しているため）。位置と形の見当はつくので、この輪郭を使っている（層1を OpenStreetMap に替える基準は「Natural Earth のほうが小さすぎる場合」だけ。3-3 付録A）。'],
        src13='国境・都市（Natural Earth にモナコの1級区分・都市は1つずつ）',
        fig='東経7.355〜7.449度・北緯43.71〜43.772度'),
    'CHE': dict(W31, dir=os.path.join(DATA, 'CHE'),
        terms='<b>区分の呼び名</b>：26の区分は、Natural Earth では <b>Canton</b>（フランス語）・<b>Kanton</b>（ドイツ語）・<b>Chantun</b>（ロマンシュ語）とある（読みはカントン、チャントゥン）。<b>どの言葉を使うかは州ごとに違う</b>が、どの州がどの言葉かは Natural Earth に入っていない。イタリア語の呼び名も入っていない。', terms_reading=True, name='スイス', geofabrik='europe/switzerland-latest.osm.pbf', phi0=46.80,
        description='スイスの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（州・都市）の3層を重ねた地図。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (5.6, 10.8), 'lat': (45.5, 48.1), 'title': 'スイス全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None,
        notes=['スイスの憲法には首都の定めが無く、ベルンは「連邦都市」（政府と議会の所在地）です（3-1 §05）。'],
        src13='国境・26州（カントン）・都市（人口 POP_MAX の多い順に20）',
        fig='東経5.6〜10.8度・北緯45.5〜48.1度'),
    'LIE': dict(W31, dir=os.path.join(DATA, 'LIE'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない。', terms_reading=False, name='リヒテンシュタイン', geofabrik='europe/liechtenstein-latest.osm.pbf', phi0=47.14,
        zoom=50, fine=0.05, zoom_why='幅約4px',
        description='リヒテンシュタインの国のページ。位置と形・骨組み・区画（基礎自治体）の3層を重ねた地図（この国の図だけ50倍）。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (9.44, 9.66), 'lat': (47.02, 47.29), 'title': 'リヒテンシュタイン全土'}},
        regions={}, region_fill={}, admin1_word='自治体', city_strip=None,
        notes=['<b>Natural Earth の輪郭は137km² で、公式の160km² より小さい（86%）</b>。層1を OpenStreetMap に替える基準（実際の3分の2未満）には届かないので、この輪郭を使っている（3-3 付録A）。'],
        src13='国境・11の基礎自治体・都市（Natural Earth にリヒテンシュタインの都市は1つ）',
        fig='東経9.44〜9.66度・北緯47.02〜47.29度'),
    'DEU': dict(W31, dir=os.path.join(DATA, 'DEU'),
        terms='<b>区分の呼び名</b>：16の区分は <b>Land</b>（ラント）。', terms_reading=True, name='ドイツ', geofabrik='europe/germany-latest.osm.pbf', phi0=51.03,
        description='ドイツの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（州・都市）の3層を重ねた地図。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (5.5, 15.4), 'lat': (47.0, 55.3), 'title': 'ドイツ全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None, notes=[],
        src13='国境・16州・都市（人口 POP_MAX の多い順に20）',
        fig='東経5.5〜15.4度・北緯47.0〜55.3度'),
    'AUT': dict(W31, dir=os.path.join(DATA, 'AUT'),
        terms='<b>区分の呼び名</b>：9の区分は <b>Bundesland</b>（ブンデスラント）／<b>Land</b>（ラント）。Natural Earth では「Bundesländ|Länd」と綴りが崩れている。', terms_reading=True, name='オーストリア', geofabrik='europe/austria-latest.osm.pbf', phi0=47.59,
        description='オーストリアの国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画（州・都市）の3層を重ねた地図。メモリーバース 3-1 西ヨーロッパ。',
        panels={'main': {'lon': (9.2, 17.5), 'lat': (46.1, 49.3), 'title': 'オーストリア全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None, notes=[],
        src13='国境・9州・都市（人口 POP_MAX の多い順に20。Natural Earth にオーストリアの都市は9しか無い）',
        fig='東経9.2〜17.5度・北緯46.1〜49.3度'),
})


def outline(cc):
    """その国の輪郭。Natural Earth v5.1.2 の国。ただし outline_osm のある国（バチカン・ジブラルタル・オーランド諸島）は OSM の輪郭
    （Natural Earth の形が使えないため。extract.sh が data/<国>/outline.geojson に切り出す。DESIGN.md §112）"""
    import json
    from shapely.geometry import shape
    c = COUNTRIES[cc]
    if c.get('outline_osm'):
        fs = json.load(open(os.path.join(c['dir'], 'outline.geojson')))['features']
        f = next(f for f in fs if str(f['properties'].get('@id')) == str(c['outline_osm']) and f['geometry']['type'] in ('Polygon', 'MultiPolygon'))
        return shape(f['geometry'])
    ne0 = json.load(open(os.path.join(NE, 'ne_10m_admin_0_countries.geojson')))
    return shape(next(f for f in ne0['features'] if f['properties']['ADM0_A3'] == cc)['geometry'])


# ---- 3-2 南ヨーロッパの17の単位（本土の重心の経度で東経0度から東回り。東経0度より西のポルトガル・ジブラルタル・スペインが最後）----
# 倍率は §100.11 の規則（100px 未満だけ、300〜700px に収まる 10・20・50・100・200・1000倍のうち最小）。
#   スロベニア96px・北マケドニア84px・モンテネグロ75px は、10倍で700px を超えるので上げない（DESIGN.md §112.2）
# 地方（region）：Natural Earth の region が**全部の区分に入っている国だけ**使う。一部にしか無い・誤りがある国は使わず、注記に書く
W32 = dict(up_href='memoryverse_3-2.html', up_label='3-2 南ヨーロッパ')
D32 = lambda nm, extra='': f'{nm}の国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画の3層を重ねた地図{extra}。メモリーバース 3-2 南ヨーロッパ。'
IT_REG = {'Abruzzo': 'アブルッツォ', 'Apulia': 'プーリア', 'Basilicata': 'バジリカータ', 'Calabria': 'カラブリア', 'Campania': 'カンパーニア',
          'Emilia-Romagna': 'エミリア＝ロマーニャ', 'Friuli-Venezia Giulia': 'フリウリ＝ヴェネツィア・ジュリア', 'Lazio': 'ラツィオ', 'Liguria': 'リグーリア',
          'Lombardia': 'ロンバルディア', 'Marche': 'マルケ', 'Molise': 'モリーゼ', 'Piemonte': 'ピエモンテ', 'Sardegna': 'サルデーニャ', 'Sicily': 'シチリア',
          'Toscana': 'トスカーナ', 'Trentino-Alto Adige': 'トレンティーノ＝アルト・アディジェ', 'Umbria': 'ウンブリア', "Valle d'Aosta": 'ヴァッレ・ダオスタ', 'Veneto': 'ヴェネト'}
ES_REG = {'Andalucía': 'アンダルシア', 'Aragón': 'アラゴン', 'Asturias': 'アストゥリアス', 'Canary Is.': 'カナリア諸島', 'Cantabria': 'カンタブリア',
          'Castilla y León': 'カスティーリャ・イ・レオン', 'Castilla-La Mancha': 'カスティーリャ＝ラ・マンチャ', 'Cataluña': 'カタルーニャ', 'Ceuta': 'セウタ',
          'Extremadura': 'エストレマドゥーラ', 'Foral de Navarra': 'ナバラ', 'Galicia': 'ガリシア', 'Islas Baleares': 'バレアレス諸島', 'La Rioja': 'ラ・リオハ',
          'Madrid': 'マドリード', 'Melilla': 'メリリャ', 'Murcia': 'ムルシア', 'País Vasco': 'バスク', 'Valenciana': 'バレンシア'}
SI_REG = {k: k for k in ['Gorenjska', 'Goriška', 'Jugovzhodna Slovenija', 'Koroška', 'Notranjsko-kraška', 'Obalno-kraška', 'Osrednjeslovenska',
                         'Podravska', 'Pomurska', 'Savinjska', 'Spodnjeposavska', 'Zasavska']}
NOREG = lambda have, tot, what: f'Natural Earth の region（区分をまとめる単位）は、{tot}の区分のうち{have}にしか入っていない{what}ので、この図には使っていない（層3の「地方」は「なし」と出る）。'
CITYN = lambda nm, n: f'都市（人口 POP_MAX の多い順に20。Natural Earth に{nm}の都市は{n}しか無い）' if n < 20 else '都市（人口 POP_MAX の多い順に20）'
BORDER = 'この地図の国境は、2-1 §08 で決めたとおり実効支配で描いています。'
COUNTRIES.update({
    'AND': dict(W32, dir=os.path.join(DATA, 'AND'), name='アンドラ', geofabrik='europe/andorra-latest.osm.pbf', phi0=42.54,
        zoom=50, fine=0.05, zoom_why='幅約12px', description=D32('アンドラ', '（この国の図だけ50倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（7つの区分がある）。', terms_reading=False,
        panels={'main': {'lon': (1.363, 1.808), 'lat': (42.386, 42.692), 'title': 'アンドラ全土'}},
        regions={}, region_fill={}, admin1_word='区', city_strip=None, notes=[],
        src13='国境・7つの区・' + CITYN('アンドラ', 1), fig='東経1.363〜1.808度・北緯42.386〜42.692度'),
    'ITA': dict(W32, dir=os.path.join(DATA, 'ITA'), name='イタリア', geofabrik='europe/italy-latest.osm.pbf', phi0=43.48,
        description=D32('イタリア'),
        terms='<b>区分の呼び名</b>：Natural Earth では110の区分の種類が <b>Province</b>（プロヴィンチェ）とあり、20のまとまりが region に入っている（層3の「州」）。', terms_reading=True,
        panels={'main': {'lon': (6.203, 18.917), 'lat': (35.089, 47.485), 'title': '本土・シチリア島・サルデーニャ島'}},
        regions=IT_REG, region_fill={}, region_word='州', region_suffix='', region_fs=12, region_ls=1, admin1_word='県', city_strip=None,
        notes=['サンマリノとバチカンは、イタリアに囲まれた別の国（3-2 §06）。この図ではイタリアの中の小さな穴になる。'],
        src13='国境・海岸線・110県・20州・' + CITYN('イタリア', 56), fig='東経6.203〜18.917度・北緯35.089〜47.485度'),
    'SMR': dict(W32, rivers_outside_note='どれもイタリア側を流れる川で（国から1〜11km）、国の外にある。', dir=os.path.join(DATA, 'SMR'), name='サンマリノ', geofabrik='europe/italy-latest.osm.pbf', phi0=43.94,
        zoom=100, fine=0.02, zoom_why='縦約4px', description=D32('サンマリノ', '（この国の図だけ100倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（9つの区分がある）。', terms_reading=False,
        panels={'main': {'lon': (12.373, 12.505), 'lat': (43.879, 43.995), 'title': 'サンマリノ全土'}},
        regions={}, region_fill={}, admin1_word='区', city_strip=None,
        notes=['サンマリノは、周りをすべてイタリアに囲まれている（3-2 §06）。層2は OpenStreetMap のイタリアの抽出（サンマリノを含む）から、この国の輪郭の中を数えている。'],
        src13='国境・9つの区・' + CITYN('サンマリノ', 1), fig='東経12.373〜12.505度・北緯43.879〜43.995度'),
    'VAT': dict(W32, rivers_outside_note='どれもイタリア（ローマ）を流れる川で、国の外にある（テヴェレ川は国から0.6km）。', dir=os.path.join(DATA, 'VAT'), name='バチカン', geofabrik='europe/italy-latest.osm.pbf', phi0=41.90,
        zoom=1000, fine=0.002, zoom_why='約0.4px の点', description=D32('バチカン', '（この国の図だけ1000倍）'),
        outline_osm=36989, outline_why='Natural Earth（1:1000万）の輪郭は7つの点・0.01km² しかなく、形として使えないため。OpenStreetMap の輪郭は257の点・0.49km²。',
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（国全体で1つ）。', terms_reading=False,
        panels={'main': {'lon': (12.444, 12.460), 'lat': (41.899, 41.909), 'title': 'バチカン全土'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=['バチカンは、周りをすべてイタリア（ローマ）に囲まれている（3-2 §06）。層2は OpenStreetMap のイタリアの抽出から、この国の輪郭の中を数えている。'],
        src13='区分（国全体で1つ）・' + CITYN('バチカン', 1) + '。層3の区分の線は Natural Earth の形なので、層1（OpenStreetMap）の輪郭とは重ならない', fig='東経12.444〜12.460度・北緯41.899〜41.909度'),
    'MLT': dict(W32, dir=os.path.join(DATA, 'MLT'), name='マルタ', geofabrik='europe/malta-latest.osm.pbf', phi0=35.89,
        zoom=50, fine=0.05, zoom_why='幅約14px', description=D32('マルタ', '（この国の図だけ50倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（68の区分があり、3つのまとまりが region に入っている。層3の「地域」）。', terms_reading=False,
        panels={'main': {'lon': (14.138, 14.613), 'lat': (35.755, 36.122), 'title': 'マルタ島・ゴゾ島'}},
        regions={'Malta Xlokk': 'Malta Xlokk', 'Malta Majjistral': 'Malta Majjistral', 'Gozo': 'Gozo'}, region_fill={}, region_word='地域', region_suffix='', region_fs=12, region_ls=1,
        admin1_word='区', city_strip=None, notes=[],
        src13='国境・海岸線・68の区・3つの地域・' + CITYN('マルタ', 1), fig='東経14.138〜14.613度・北緯35.755〜36.122度'),
    'SVN': dict(W32, rivers_outside_note='Sotla / Sutla は国境の川で（OpenStreetMap の国境の線に沿って流れる。59.8km のうち58.0km）、国の外にあるわけではない。<b>Natural Earth の粗い国境の線の外側に入るため、この図には描いていない。</b>', dir=os.path.join(DATA, 'SVN'), name='スロベニア', geofabrik='europe/slovenia-latest.osm.pbf', phi0=46.12,
        description=D32('スロベニア'),
        terms='<b>区分の呼び名</b>：Natural Earth では193の区分のうち181の種類が <b>Opcine</b>（オプチネ）、12が <b>Statisticna Regije</b>（スタティスティチュナ・レギイェ）とあり、12のまとまりが region に入っている（層3の「統計地域」）。', terms_reading=True,
        panels={'main': {'lon': (12.965, 16.915), 'lat': (45.024, 47.264), 'title': 'スロベニア全土'}},
        regions=SI_REG, region_fill={}, region_word='統計地域', region_suffix='', region_fs=11, region_ls=1, admin1_word='自治体', city_strip=None,
        notes=['1度44pxで幅約96px と小さいが、形は読めるので倍率を上げていない（ベルギー126px と同じ扱い。拡大表示で詳しく見られる）。'],
        src13='国境・海岸線・193の区分・12の統計地域・' + CITYN('スロベニア', 2), fig='東経12.965〜16.915度・北緯45.024〜47.264度'),
    'HRV': dict(W32, dir=os.path.join(DATA, 'HRV'), name='クロアチア', geofabrik='europe/croatia-latest.osm.pbf', phi0=45.15,
        description=D32('クロアチア'),
        terms='<b>区分の呼び名</b>：Natural Earth では20の区分の種類が <b>Županija</b>（ジュパニヤ）、首都の1つが <b>Grad</b>（グラード）。', terms_reading=True,
        panels={'main': {'lon': (13.101, 19.808), 'lat': (42.016, 46.947), 'title': 'クロアチア全土'}},
        regions={}, region_fill={}, admin1_word='郡', city_strip=None,
        notes=['南の端のドゥブロヴニクのあたりは、ボスニア・ヘルツェゴビナの海岸（ネウム）で本土から切れている。モンテネグロと接するのはこの部分だけ。',
               NOREG(1, 21, '（しかもスロベニアの地域名 Jugovzhodna Slovenija が入っている）')],
        src13='国境・海岸線・21の区分・' + CITYN('クロアチア', 10), fig='東経13.101〜19.808度・北緯42.016〜46.947度'),
    'BIH': dict(W32, dir=os.path.join(DATA, 'BIH'), name='ボスニア・ヘルツェゴビナ', geofabrik='europe/bosnia-herzegovina-latest.osm.pbf', phi0=44.17,
        description=D32('ボスニア・ヘルツェゴビナ'),
        terms='<b>区分の呼び名</b>：Natural Earth では18の区分の種類が <b>Županija|kanton</b>・<b>Canton</b>（10）、<b>Region</b>（7）、<b>Condominium</b>（1、ブルチコ）とばらばらで、2つのまとまりが region に入っている（層3の「構成体」。Natural Earth の綴りは Repuplika Srpska）。', terms_reading=False,
        panels={'main': {'lon': (15.316, 20.019), 'lat': (42.159, 45.685), 'title': 'ボスニア・ヘルツェゴビナ全土'}},
        regions={'Federacija Bosna i Hercegovina': 'ボスニア・ヘルツェゴビナ連邦', 'Repuplika Srpska': 'スルプスカ共和国'}, region_fill={},
        region_word='構成体', region_suffix='', region_fs=12, region_ls=1, admin1_word='区分', city_strip=None,
        notes=['海に面しているのは、南のネウムのあたりだけ（Natural Earth の形で約18km）。'],
        src13='国境・海岸線・18の区分・2つの構成体・' + CITYN('ボスニア・ヘルツェゴビナ', 6), fig='東経15.316〜20.019度・北緯42.159〜45.685度'),
    'MNE': dict(W32, rivers_outside_note='Lumi i Cemit は国境の川ではなく（OpenStreetMap の国境の線に沿うのは0.6km）、ほとんどがアルバニア側を流れる（国の中は0.1km）。', dir=os.path.join(DATA, 'MNE'), name='モンテネグロ', geofabrik='europe/montenegro-latest.osm.pbf', phi0=42.78,
        description=D32('モンテネグロ'),
        terms='<b>区分の呼び名</b>：Natural Earth では21の区分の種類が <b>Opština</b>（オプシュティナ）。', terms_reading=True,
        panels={'main': {'lon': (18.034, 20.755), 'lat': (41.452, 43.948), 'title': 'モンテネグロ全土'}},
        regions={}, region_fill={}, admin1_word='自治体', city_strip=None,
        notes=['1度44pxで縦約75px と小さいが、倍率を上げていない（10倍だと700px を超え、規則の倍率に合わない。拡大表示で詳しく見られる）。'],
        src13='国境・海岸線・21の自治体・' + CITYN('モンテネグロ', 1), fig='東経18.034〜20.755度・北緯41.452〜43.948度'),
    'ALB': dict(W32, dir=os.path.join(DATA, 'ALB'), name='アルバニア', geofabrik='europe/albania-latest.osm.pbf', phi0=41.14,
        description=D32('アルバニア'),
        terms='<b>区分の呼び名</b>：Natural Earth では12の区分の種類が <b>Qark</b>（チャルク）。', terms_reading=True,
        panels={'main': {'lon': (18.872, 21.437), 'lat': (39.237, 43.055), 'title': 'アルバニア全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None, notes=[],
        src13='国境・海岸線・12州・' + CITYN('アルバニア', 26), fig='東経18.872〜21.437度・北緯39.237〜43.055度'),
    'SRB': dict(W32, dir=os.path.join(DATA, 'SRB'), name='セルビア', geofabrik='europe/serbia-latest.osm.pbf', phi0=44.21,
        description=D32('セルビア'),
        terms='<b>区分の呼び名</b>：Natural Earth では24の区分の種類が <b>Okrug</b>（オクルグ）、首都ベオグラードが <b>Grad</b>（グラード）。', terms_reading=True,
        panels={'main': {'lon': (18.445, 23.385), 'lat': (41.835, 46.574), 'title': 'セルビア全土'}},
        regions={}, region_fill={}, admin1_word='郡', city_strip=None,
        notes=[BORDER + 'セルビアはコソボを自国の一部と主張しているが、この地図ではコソボを別の区域として描いている（3-2 §06）。', NOREG(11, 25, '')],
        src13='国境・25の区分・' + CITYN('セルビア', 7), fig='東経18.445〜23.385度・北緯41.835〜46.574度'),
    'KOS': dict(W32, dir=os.path.join(DATA, 'KOS'), name='コソボ', geofabrik='europe/kosovo-latest.osm.pbf', phi0=42.57,
        zoom=10, fine=0.2, zoom_why='縦約62px', description=D32('コソボ', '（この国の図だけ10倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth では30の区分の種類が <b>Okrug</b>（オクルグ）とある。', terms_reading=True,
        panels={'main': {'lon': (19.815, 21.983), 'lat': (41.634, 43.473), 'title': 'コソボ全土'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=[BORDER + 'コソボは自らの政府が治めていて、セルビアが自国の一部と主張している。承認している国の数は、数える人で違う（3-2 §06）。',
               'Natural Earth の region（7つ）は、セルビア語の地名（Đakovica・Uroševac など）で入っている。どちらかの言葉の地名だけを図に出すことになるので、使っていない（層3の「地方」は「なし」と出る）。'],
        src13='国境・30の区分・' + CITYN('コソボ', 3), fig='東経19.815〜21.983度・北緯41.634〜43.473度'),
    'MKD': dict(W32, rivers_outside_note='Елешница は国境の川ではなく（OpenStreetMap の国境の線に沿う部分は無い）、国の外を流れる。', dir=os.path.join(DATA, 'MKD'), name='北マケドニア', geofabrik='europe/macedonia-latest.osm.pbf', phi0=41.60,
        description=D32('北マケドニア'),
        terms='<b>区分の呼び名</b>：Natural Earth では84の区分の種類が <b>Statistical Region</b>（72）・<b>Municipality</b>（10）・<b>Opština</b>（2、オプシュティナ）とばらばら。', terms_reading=True,
        panels={'main': {'lon': (20.044, 23.410), 'lat': (40.449, 42.770), 'title': '北マケドニア全土'}},
        regions={}, region_fill={}, admin1_word='自治体', city_strip=None,
        notes=['1度44pxで幅約84px と小さいが、倍率を上げていない（10倍だと700px を超え、規則の倍率に合わない。拡大表示で詳しく見られる）。', NOREG(69, 84, '')],
        src13='国境・84の区分・' + CITYN('北マケドニア', 3), fig='東経20.044〜23.410度・北緯40.449〜42.770度'),
    'GRC': dict(W32, dir=os.path.join(DATA, 'GRC'), name='ギリシャ', geofabrik='europe/greece-latest.osm.pbf', phi0=39.46,
        description=D32('ギリシャ'),
        terms='<b>区分の呼び名</b>：Natural Earth では13の区分の種類が <b>Diamerismata</b>（ディアメリスマタ）、1つ（アトス山）が <b>Aftonomi Monastiki Politia</b>（自治修道院国家）。', terms_reading=True,
        panels={'main': {'lon': (19.226, 28.640), 'lat': (34.415, 42.150), 'title': '本土とエーゲ海・イオニア海・クレタ島'}},
        regions={}, region_fill={}, admin1_word='地方', city_strip=None, notes=[NOREG(4, 14, '')],
        src13='国境・海岸線・14の区分・' + CITYN('ギリシャ', 30), fig='東経19.226〜28.640度・北緯34.415〜42.150度'),
    'PRT': dict(W32, dir=os.path.join(DATA, 'PRT'), name='ポルトガル', geofabrik='europe/portugal-latest.osm.pbf', phi0=39.66,
        description=D32('ポルトガル', '（マデイラの図だけ10倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth では18の区分の種類が <b>Distrito</b>（ディシュトリト）、2つ（アゾレス・マデイラ）が <b>Regiões autônoma</b>（自治地域）。', terms_reading=True,
        panels={'main': {'lon': (-9.897, -5.806), 'lat': (36.566, 42.554), 'title': '本土'},
                'azores': {'lon': (-31.685, -24.612), 'lat': (36.534, 40.128), 'title': 'アゾレス諸島（本土と同じ縮尺）'},
                'madeira': {'lon': (-17.332, -16.195), 'lat': (32.412, 33.191), 'title': 'マデイラ諸島', 'zoom': 10, 'fine': 0.2, 'zoom_why': '幅約36px'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None,
        notes=['図の外にある島：<b>セルヴァジェン諸島</b>（北緯30.1度・西経15.9度。マデイラ自治地域）。', NOREG(18, 20, '（「Norte, Centro」のように2つが並んだ値もある）')],
        src13='国境・海岸線・18県と2つの自治地域・' + CITYN('ポルトガル', 24), fig='本土は西経9.897〜5.806度・北緯36.566〜42.554度、アゾレス諸島は西経31.685〜24.612度・北緯36.534〜40.128度、マデイラ諸島は西経17.332〜16.195度・北緯32.412〜33.191度'),
    'GIB': dict(W32, rivers_outside_note='どれもスペイン側を流れる川で（国から6km 以上）、国の外にある。', dir=os.path.join(DATA, 'GIB'), name='ジブラルタル', geofabrik='europe/spain-latest.osm.pbf', phi0=36.14,
        zoom=200, fine=0.01, zoom_why='縦約2px', description=D32('ジブラルタル', '（この図だけ200倍）'),
        outline_osm=6358272, outline_why='Natural Earth（1:1000万）の輪郭は3.69km² で形が粗いため。OpenStreetMap の陸の境界（boundary=land_area、6.59km²）を使う。領海まで含む境界（93.7km²）は使わない。',
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（全体で1つ）。', terms_reading=False,
        panels={'main': {'lon': (-5.373, -5.332), 'lat': (36.103, 36.161), 'title': 'ジブラルタル全土'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=['ジブラルタルはイギリスの海外領土で、スペインが主権を主張している（3-2 §06）。Natural Earth でも国ではなく係争の単位（Disputed）として入っている。層2は OpenStreetMap のスペインの抽出から、この輪郭の中を数えている。'],
        src13='区分（全体で1つ）・' + CITYN('ジブラルタル', 1) + '。層3の区分の線は Natural Earth の形なので、層1（OpenStreetMap）の輪郭とは重ならない', fig='西経5.373〜5.332度・北緯36.103〜36.161度'),
    'ESP': dict(W32, dir=os.path.join(DATA, 'ESP'), name='スペイン', geofabrik='europe/spain-latest.osm.pbf', phi0=40.36,
        description=D32('スペイン'),
        terms='<b>区分の呼び名</b>：Natural Earth では52の区分のうち50の種類が <b>Comunidad Autónoma</b>（コムニダ・アウトノマ）、2つ（セウタ・メリリャ）が <b>Ciudades Autónomas</b>（シウダデス・アウトノマス）とある。ただし50の区分は自治州そのものではなく、自治州の名前は region のほうに入っている（層3の「自治州」、19）。種類の欄と区分の単位が合っていない。', terms_reading=True,
        panels={'main': {'lon': (-9.692, 4.737), 'lat': (34.772, 44.193), 'title': '本土・バレアレス諸島・セウタ・メリリャ'},
                'canarias': {'lon': (-18.567, -13.018), 'lat': (27.242, 29.689), 'title': 'カナリア諸島（本土と同じ縮尺）'}},
        regions=ES_REG, region_fill={}, region_word='自治州', region_suffix='', region_fs=12, region_ls=1, admin1_word='県', city_strip=None,
        notes=['<b>セウタ</b>（北緯35.9度・西経5.3度）と<b>メリリャ</b>（北緯35.3度・西経2.9度）は、アフリカの北岸にあるスペインの都市で、本土の図に入っている。モロッコと陸で接するのは、この2つの部分だけ。'],
        src13='国境・海岸線・52の区分・19の自治州・' + CITYN('スペイン', 49), fig='本土は西経9.692度〜東経4.737度・北緯34.772〜44.193度、カナリア諸島は西経18.567〜13.018度・北緯27.242〜29.689度'),
})


# ---- 3-3 北ヨーロッパの15単位（本土の重心の経度で東経0度から東回り。東経0度より西のアイスランド〜ジャージーの7つが最後）----
# 倍率は §100.11 の規則。点線の格子は、オーランド・フェローだけ0.5度（高緯度で経度0.2度が約44px しかなく、ラベルが詰まる）。ガーンジーは本島だけ（オルダニー島まで入れると 300〜700px に合う倍率が無い。DESIGN.md §121）
# 層1は Natural Earth。ただしオーランド諸島は OSM の海岸線から作った輪郭（Natural Earth は実際の陸地の62%。§112.1）
# 層3の区分：Natural Earth の区分が誤っている単位（ガーンジー・フェロー・オーランド）は使わない（admin1_off）
W33 = dict(up_href='memoryverse_3-3.html', up_label='3-3 北ヨーロッパ')
D33 = lambda nm, extra='': f'{nm}の国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画の3層を重ねた地図{extra}。メモリーバース 3-3 北ヨーロッパ。'
NOT_STATE = lambda nm, sov: f'{nm}は主権国家ではなく、{sov}（3-3 §06）。Natural Earth では別の単位として入っているので、国と同じ形のページにしている。'
LV_REG = {'Vidzeme': 'ヴィドゼメ', 'Riga': 'リガ', 'Latgale': 'ラトガレ', 'Zemgale': 'ゼムガレ', 'Kurzeme': 'クルゼメ'}
IE_REG = {'Border': 'ボーダー', 'Dublin': 'ダブリン', 'Mid-East': '中東部', 'South-East': '南東部', 'South-West': '南西部',
          'Mid-West': '中西部', 'West': '西部', 'Midlands': 'ミッドランズ'}
LV_JA_WRONG = ['Rujienas', 'Mazsalacas', 'Nauksenu', 'Apes', 'Smiltenes', 'Strencu', 'Beverinas', 'Burtnieku', 'Kocenu', 'Vecpiebalgas',
               'Raunas', 'Priekulu', 'Pargaujas', 'Jaunpiebalgas', 'Lubanas', 'Varaklanu', 'Amatas', 'Erglu', 'Cesvaines', 'Ligatnes']
COUNTRIES.update({
    'DNK': dict(W33, dir=os.path.join(DATA, 'DNK'), name='デンマーク', geofabrik='europe/denmark-latest.osm.pbf', phi0=56.22,
        description=D33('デンマーク'),
        terms='<b>区分の呼び名</b>：5つの区分は <b>Region</b>（レギオン）。', terms_reading=True,
        panels={'main': {'lon': (8.094, 15.151), 'lat': (54.569, 57.751), 'title': 'ユトランド半島・島々・ボーンホルム島'}},
        regions={}, region_fill={}, admin1_word='地域', city_strip=None,
        notes=['グリーンランドとフェロー諸島はデンマーク王国の一部だが、Natural Earth では別の単位で、この図には入れていない（3-3 §06。グリーンランドは北アメリカに入る）。'],
        src13='国境・海岸線・5つの地域・' + CITYN('デンマーク', 12), fig='東経8.094〜15.151度・北緯54.569〜57.751度'),
    'NOR': dict(W33, dir=os.path.join(DATA, 'NOR'), name='ノルウェー', geofabrik='europe/norway-latest.osm.pbf', phi0=63.78,
        description=D33('ノルウェー'),
        terms='<b>区分の呼び名</b>：Natural Earth では19の区分の種類が <b>Fylke</b>（フュルケ）、スヴァールバル諸島が Territory とある。', terms_reading=True,
        panels={'main': {'lon': (4.644, 31.077), 'lat': (57.993, 71.165), 'title': '本土と沿岸の島'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None,
        notes=['図の外にある島（Natural Earth でノルウェーの形に含まれる3つ）：<b>スヴァールバル諸島</b>（北緯76.5〜80.8度・東経10〜33度）、<b>ヤンマイエン島</b>（北緯71.0度・西経8.4度）、<b>ブーベ島</b>（南大西洋、南緯54.4度・東経3.4度）。埋める加工はしない。スヴァールバル諸島の扱いは 3-3 §06。',
               '層3の19の県は、<b>2018年より前の区分</b>です（2018年に1つになったヌール・トロンデラーグとソール・トロンデラーグが別々に入っている）。Natural Earth v5.1.2 がこの区分のままなので、直さずに描いています。ノルウェー統計局の県の分類では、2024年1月1日から15県です（2026年9月29日確認）。'],
        src13='国境・海岸線・19県とスヴァールバル諸島・' + CITYN('ノルウェー', 34), fig='東経4.644〜31.077度・北緯57.993〜71.165度（本土と沿岸の島）'),
    'SWE': dict(W33, dir=os.path.join(DATA, 'SWE'), name='スウェーデン', geofabrik='europe/sweden-latest.osm.pbf', phi0=62.44,
        description=D33('スウェーデン'),
        terms='<b>区分の呼び名</b>：21の区分は <b>Län</b>（レーン。Natural Earth の綴りは「Laen|län」）。', terms_reading=True,
        panels={'main': {'lon': (11.108, 24.163), 'lat': (55.343, 69.036), 'title': 'スウェーデン全土'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None, notes=[],
        src13='国境・海岸線・21県・' + CITYN('スウェーデン', 34), fig='東経11.108〜24.163度・北緯55.343〜69.036度'),
    'ALD': dict(W33, dir=os.path.join(DATA, 'ALD'), name='オーランド諸島', geofabrik='europe/finland-latest.osm.pbf', phi0=60.25,     # 本土（オーランド本島）の重心。OSM の輪郭で
        zoom=10, fine=0.5, zoom_why='幅約40px', description=D33('オーランド諸島', '（この図だけ10倍）'),
        outline_osm=1650407, outline_coast={'bbox': (19.0, 59.6, 21.5, 60.8), 'min_km2': 0.0625, 'tol': 0.0003},
        outline_why=('Natural Earth（1:1000万）の輪郭は942km² で、細かい島が落ちて実際の陸地（OpenStreetMap の海岸線で1,517km²）の62%しかないため。'
                     'OpenStreetMap の行政の境界（海まで含む）の中の、海岸線で閉じた島を集めた。島は15,753あり、この図（10倍、1km が約4px）で1px 四方に満たない'
                     '0.0625km² 未満の島は描いていない。'),
        terms=None, admin1_off=True,
        panels={'main': {'lon': (19.25, 21.2), 'lat': (59.75, 60.62), 'title': 'オーランド諸島全体'}},
        regions={}, region_fill={}, admin1_word='自治体', city_strip=None,
        notes=[NOT_STATE('オーランド諸島', 'フィンランドの自治領'),
               'Natural Earth の区分（自治体）は11しか入っておらず、陸地の半分ほどしか覆っていない（OpenStreetMap には16の自治体がある）。全部の区分に入っていないので使っていない（層3の区分名は「なし」と出る）。',
               '層2は OpenStreetMap のフィンランドの抽出から、この輪郭の中を数えている。'],
        src13=CITYN('オーランド諸島', 1) + '。区分は使っていない（上の注記）', fig='東経19.25〜21.2度・北緯59.75〜60.62度'),
    'LTU': dict(W33, dir=os.path.join(DATA, 'LTU'), name='リトアニア', geofabrik='europe/lithuania-latest.osm.pbf', phi0=55.32,
        description=D33('リトアニア'),
        terms='<b>区分の呼び名</b>：10の区分は <b>Apskritis</b>（アプスクリティス）。', terms_reading=True,
        panels={'main': {'lon': (20.925, 26.801), 'lat': (53.887, 56.443), 'title': 'リトアニア全土'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None,
        notes=['西で接するロシアは、飛び地のカリーニングラード州（ロシアの本土とは陸でつながっていない）。'],
        src13='国境・海岸線・10県・' + CITYN('リトアニア', 5), fig='東経20.925〜26.801度・北緯53.887〜56.443度'),
    'LVA': dict(W33, dir=os.path.join(DATA, 'LVA'), name='ラトビア', geofabrik='europe/latvia-latest.osm.pbf', phi0=56.86,
        description=D33('ラトビア'),
        terms='<b>区分の呼び名</b>：Natural Earth では119の区分のうち110の種類が <b>Novads</b>（ノヴァツ）、9つが <b>Republikas pilsētas</b>（共和国市）。5つのまとまりが region に入っている（層3の「地方」）。', terms_reading=True,
        panels={'main': {'lon': (20.969, 28.217), 'lat': (55.667, 58.075), 'title': 'ラトビア全土'}},
        regions=LV_REG, region_fill={}, region_word='地方', region_suffix='', region_fs=12, region_ls=1, admin1_word='自治体', city_strip=None,
        admin1_ja_wrong=LV_JA_WRONG,
        notes=['層3の119の区分は、<b>2021年の自治体の改革より前の区分</b>です。Natural Earth v5.1.2 がこの区分のままなので、直さずに描いています。ラトビアの環境保護・地域開発省によると、改革で119の自治体が43にまとめられました（2026年9月29日確認。同じページに「いまは42」という記述もある）。',
               '区分の名前のうち20（Rujienas・Smiltenes など、ヴィドゼメ地方の自治体）は、Natural Earth の日本語名が誤って「ヴァルミエラ」になっているので、原語で出している。'],
        src13='国境・海岸線・119の区分・5つの地方・' + CITYN('ラトビア', 6), fig='東経20.969〜28.217度・北緯55.667〜58.075度'),
    'EST': dict(W33, dir=os.path.join(DATA, 'EST'), name='エストニア', geofabrik='europe/estonia-latest.osm.pbf', phi0=58.68,
        description=D33('エストニア'),
        terms='<b>区分の呼び名</b>：15の区分は <b>Maakond</b>（マーコンド）。Natural Earth ではサーレ県だけ種類がラトビア語の Novads になっている。', terms_reading=True,
        panels={'main': {'lon': (21.832, 28.186), 'lat': (57.516, 59.671), 'title': 'エストニア全土'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None, notes=[],
        src13='国境・海岸線・15県・' + CITYN('エストニア', 7), fig='東経21.832〜28.186度・北緯57.516〜59.671度'),
    'FIN': dict(W33, dir=os.path.join(DATA, 'FIN'), name='フィンランド', geofabrik='europe/finland-latest.osm.pbf', phi0=64.27,
        description=D33('フィンランド'),
        terms='<b>区分の呼び名</b>：Natural Earth では18の区分の種類が <b>Lääni</b>（13。レーニ）・<b>Maakunta|landskap</b>（3。マークンタ）などとばらばらだが、区分そのものは18の maakunta（地域）。', terms_reading=True,
        panels={'main': {'lon': (20.623, 31.57), 'lat': (59.811, 70.075), 'title': 'フィンランド全土（オーランド諸島を除く）'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None,
        notes=['オーランド諸島（西の群島）はフィンランドの自治領で、Natural Earth では別の単位。この図には入れておらず、層2もオーランド諸島の中は数えていない（3-3 §06）。'],
        src13='国境・海岸線・18の区分・' + CITYN('フィンランド', 21), fig='東経20.623〜31.570度・北緯59.811〜70.075度'),
    'ISL': dict(W33, dir=os.path.join(DATA, 'ISL'), name='アイスランド', geofabrik='europe/iceland-latest.osm.pbf', phi0=65.00,
        description=D33('アイスランド'),
        terms='<b>区分の呼び名</b>：Natural Earth では9つの区分のうち8つの種類が <b>Landsvæði</b>（地方）、1つが Kaupstadir（市）とある。レイキャヴィークが大レイキャヴィークと別の区分になっている。', terms_reading=False,
        panels={'main': {'lon': (-24.54, -13.503), 'lat': (63.397, 66.564), 'title': 'アイスランド全土'}},
        regions={}, region_fill={}, admin1_word='地方', city_strip=None, notes=[],
        src13='海岸線・9つの区分・' + CITYN('アイスランド', 9), fig='西経24.540〜13.503度・北緯63.397〜66.564度'),
    'IRL': dict(W33, dir=os.path.join(DATA, 'IRL'), name='アイルランド', geofabrik='europe/ireland-and-northern-ireland-latest.osm.pbf', phi0=53.16,
        description=D33('アイルランド'),
        terms='<b>区分の呼び名</b>：Natural Earth では34の区分の種類が <b>Administrative County</b>（26）・<b>Traditional County</b>（4）・<b>Cathair</b>（4、市）とあり、8つのまとまりが region に入っている（層3の「地方」）。', terms_reading=False,
        panels={'main': {'lon': (-10.478, -5.994), 'lat': (51.446, 55.386), 'title': 'アイルランド全土'}},
        regions=IE_REG, region_fill={}, region_word='地方', region_suffix='', region_fs=12, region_ls=1, admin1_word='県', city_strip=None,
        notes=['アイルランド島の北東部（北アイルランド）はイギリス。この国が陸で接するのはイギリスだけ。層2は OpenStreetMap の「アイルランドと北アイルランド」の抽出から、この国の輪郭の中を数えている。'],
        src13='国境・海岸線・34の区分・8つの地方・' + CITYN('アイルランド', 15), fig='西経10.478〜5.994度・北緯51.446〜55.386度'),
    'FRO': dict(W33, dir=os.path.join(DATA, 'FRO'), name='フェロー諸島', geofabrik='europe/faroe-islands-latest.osm.pbf', phi0=62.14,
        zoom=10, fine=0.5, zoom_why='縦約44px', description=D33('フェロー諸島', '（この図だけ10倍）'),
        terms=None, admin1_off=True,
        panels={'main': {'lon': (-7.644, -6.276), 'lat': (61.394, 62.399), 'title': 'フェロー諸島全体'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=[NOT_STATE('フェロー諸島', 'デンマーク王国の自治領'),
               'Natural Earth の区分は1つだけで、全部の島が「Eysturoyar」（エストゥロイ島の地方）という名前で入っている。名前が実際と合わないので使っていない（層3の区分名は「なし」と出る）。'],
        src13=CITYN('フェロー諸島', 2) + '。区分は使っていない（上の注記）', fig='西経7.644〜6.276度・北緯61.394〜62.399度'),
    'IMN': dict(W33, dir=os.path.join(DATA, 'IMN'), name='マン島', geofabrik='europe/isle-of-man-latest.osm.pbf', phi0=54.23,
        zoom=20, fine=0.1, zoom_why='縦約16px', description=D33('マン島', '（この図だけ20倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（全体で1つ）。', terms_reading=False,
        panels={'main': {'lon': (-4.79, -4.312), 'lat': (54.057, 54.419), 'title': 'マン島全体'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=[NOT_STATE('マン島', 'イギリス王室の属領で、イギリスの一部ではない')],
        src13='区分（全体で1つ）・' + CITYN('マン島', 1), fig='西経4.790〜4.312度・北緯54.057〜54.419度'),
    'GGY': dict(W33, dir=os.path.join(DATA, 'GGY'), name='ガーンジー', geofabrik='europe/guernsey-jersey-latest.osm.pbf', phi0=49.46,
        zoom=100, fine=0.02, zoom_why='幅約5px', description=D33('ガーンジー', '（この図だけ100倍）'),
        terms=None, admin1_off=True,
        panels={'main': {'lon': (-2.673, -2.502), 'lat': (49.427, 49.516), 'title': 'ガーンジー島（本島）'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=[NOT_STATE('ガーンジー', 'イギリス王室の属領で、イギリスの一部ではない'),
               '図の外にある島（Natural Earth でガーンジーの形に含まれる3つ）：<b>オルダニー島</b>（北緯49.71度・西経2.20度。本島から約30km）、<b>サーク島</b>（北緯49.43度・西経2.36度。約12km）、<b>ハーム島</b>（北緯49.47度・西経2.45度。約4km）。オルダニー島まで入れると図が広がり、規則の倍率（長いほうの辺が300〜700px）のどれにも合わないので、本島だけを描いている（3-3 付録A）。',
               'Natural Earth の区分は1つだけで、本島・サーク島・オルダニー島の全体が「Sark」（サーク島）という名前で入っている。名前が実際と合わないので使っていない（層3の区分名は「なし」と出る）。',
               '層2は OpenStreetMap の「ガーンジーとジャージー」の抽出から、この輪郭の中を数えている。',
               '国境と海岸線は Natural Earth（1:1000万）の形で、本島は25の点で描かれています。100倍に広げると角ばって見えるのはそのためです（層2の OSM の線はもっと細かく、海岸の外へはみ出して見える道路もある）。'],
        src13='区分は使っていない（上の注記）。Natural Earth にガーンジーの都市は入っていない', fig='西経2.673〜2.502度・北緯49.427〜49.516度（本島）'),
    'GBR': dict(W33, dir=os.path.join(DATA, 'GBR'), name='イギリス', geofabrik='europe/united-kingdom-latest.osm.pbf', phi0=53.83,
        description=D33('イギリス'),
        terms='<b>区分の呼び名</b>：Natural Earth では232の区分の種類が District・Unitary Authority・London Borough など17通りに分かれている。', terms_reading=False,
        panels={'main': {'lon': (-8.7, 1.8), 'lat': (49.9, 60.9), 'title': 'グレートブリテン島・北アイルランド・島々'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=['図の外にある島：<b>ロッコール</b>（北緯57.6度・西経13.7度。Natural Earth でイギリスの形に含まれる）。',
               'ガーンジー・ジャージー・マン島はイギリス王室の属領で、イギリスの一部ではない。Natural Earth でも別の単位（3-3 §06）。',
               'Natural Earth の region（16）は、ウェールズの東西の2つの中身が入れ替わっている（カーディフが West Wales and the Valleys に入っている）ので、この図には使っていない（層3の「地方」は「なし」と出る）。'],
        src13='国境・海岸線・232の区分・' + CITYN('イギリス', 57), fig='西経8.7度〜東経1.8度・北緯49.9〜60.9度'),
    'JEY': dict(W33, dir=os.path.join(DATA, 'JEY'), name='ジャージー', geofabrik='europe/guernsey-jersey-latest.osm.pbf', phi0=49.22,
        zoom=50, fine=0.05, zoom_why='幅約7px', description=D33('ジャージー', '（この図だけ50倍）'),
        terms='<b>区分の呼び名</b>：Natural Earth に区分の種類が入っていない（全体で1つ）。', terms_reading=False,
        panels={'main': {'lon': (-2.242, -2.008), 'lat': (49.171, 49.267), 'title': 'ジャージー島'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=[NOT_STATE('ジャージー', 'イギリス王室の属領で、イギリスの一部ではない'),
               '層2は OpenStreetMap の「ガーンジーとジャージー」の抽出から、この輪郭の中を数えている。',
               '海岸線は Natural Earth（1:1000万）の形で、46の点で描かれています。50倍に広げると角ばって見えるのはそのためです（層2の OSM の線はもっと細かい）。'],
        src13='区分（全体で1つ）。Natural Earth にジャージーの都市は入っていない', fig='西経2.242〜2.008度・北緯49.171〜49.267度'),
})


# ---- 3-4 東ヨーロッパの9か国（ロシアを除く。2-1 付録A。本土の重心の経度で東経0度から東回り）----
# 9か国とも主権国家（SOVEREIGNT＝ADMIN、Disputed なし）。1度44px で長いほうの辺が100px 未満の国は無い（倍率を上げる国なし）
# 係争地は描き直さない（§124）：クリミアは Natural Earth のとおりロシアの形（ウクライナの図に入らない）、沿ドニエストルはモルドバの形の中
# 日本語名：ウクライナの首都だけ外務省の表記（2022年3月31日「ウクライナの首都等の呼称の変更」）。ほかは Natural Earth のまま（§125）
W34 = dict(up_href='memoryverse_3-4.html', up_label='3-4 東ヨーロッパ')
D34 = lambda nm, extra='': f'{nm}の国のページ。位置と形・骨組み（川・湖・道路・鉄道）・区画の3層を重ねた地図{extra}。メモリーバース 3-4 東ヨーロッパ。'
HU_REG = {'Central Hungary': '中部ハンガリー', 'Northern Hungary': '北ハンガリー', 'Northern Great Plain': '北大平原', 'Great Southern Plain': '南大平原',
          'Central Transdanubia': '中部ドゥナーントゥール', 'Western Transdanubia': '西ドゥナーントゥール', 'Southern Transdanubia': '南ドゥナーントゥール'}
MOFA_NOT_CHECKED = lambda nm: f'{nm}の地名は Natural Earth の日本語名のままで、外務省の表記と合っているかは確かめていない（3-4 付録A）。'
COUNTRIES.update({
    'CZE': dict(W34, dir=os.path.join(DATA, 'CZE'), name='チェコ', geofabrik='europe/czech-republic-latest.osm.pbf', phi0=49.74,
        description=D34('チェコ'),
        terms='<b>区分の呼び名</b>：14の区分は <b>Kraj</b>（クライ）。首都プラハもその1つ。', terms_reading=True,
        panels={'main': {'lon': (12.076, 18.837), 'lat': (48.558, 51.04), 'title': 'チェコ全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None, notes=[],
        src13='国境・14の区分・' + CITYN('チェコ', 12), fig='東経12.076〜18.837度・北緯48.558〜51.040度'),
    'HUN': dict(W34, dir=os.path.join(DATA, 'HUN'), name='ハンガリー', geofabrik='europe/hungary-latest.osm.pbf', phi0=47.17,
        description=D34('ハンガリー'),
        terms='<b>区分の呼び名</b>：Natural Earth では43の区分の種類が <b>Megye</b>（メジェ、19の県）・<b>Megyei jogú város</b>（メジェイ・ヨグー・ヴァーロシュ、県と同格の市、23）・首都ブダペストとばらばらで、7つのまとまりが region に入っている（層3の「地方」）。', terms_reading=True,
        panels={'main': {'lon': (16.094, 22.878), 'lat': (45.741, 48.569), 'title': 'ハンガリー全土'}},
        regions=HU_REG, region_fill={}, region_word='地方', region_suffix='', region_fs=12, region_ls=1, admin1_word='区分', city_strip=None, notes=[],
        src13='国境・43の区分・7つの地方・' + CITYN('ハンガリー', 20), fig='東経16.094〜22.878度・北緯45.741〜48.569度'),
    'POL': dict(W34, dir=os.path.join(DATA, 'POL'), name='ポーランド', geofabrik='europe/poland-latest.osm.pbf', phi0=52.11,
        description=D34('ポーランド'),
        terms='<b>区分の呼び名</b>：16の区分は <b>Województwo</b>（ヴォイェヴツトフォ）。', terms_reading=True,
        panels={'main': {'lon': (14.124, 24.143), 'lat': (48.994, 54.838), 'title': 'ポーランド全土'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None,
        notes=['北東で接するロシアは、飛び地のカリーニングラード州（ロシアの本土とは陸でつながっていない）。'],
        src13='国境・海岸線・16県・' + CITYN('ポーランド', 24), fig='東経14.124〜24.143度・北緯48.994〜54.838度'),
    'SVK': dict(W34, dir=os.path.join(DATA, 'SVK'), name='スロバキア', geofabrik='europe/slovakia-latest.osm.pbf', phi0=48.71,
        description=D34('スロバキア'),
        terms='<b>区分の呼び名</b>：8の区分は <b>Kraj</b>（クライ）。', terms_reading=True,
        panels={'main': {'lon': (16.844, 22.54), 'lat': (47.75, 49.602), 'title': 'スロバキア全土'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None, notes=[],
        src13='国境・8県・' + CITYN('スロバキア', 7), fig='東経16.844〜22.540度・北緯47.750〜49.602度'),
    'ROU': dict(W34, dir=os.path.join(DATA, 'ROU'), name='ルーマニア', geofabrik='europe/romania-latest.osm.pbf', phi0=45.85,
        description=D34('ルーマニア'),
        terms='<b>区分の呼び名</b>：41の区分は <b>Județ</b>（ジュデツ）、首都ブカレストは <b>Municipiu</b>（ムニチピウ）。', terms_reading=True,
        panels={'main': {'lon': (20.243, 29.7), 'lat': (43.65, 48.275), 'title': 'ルーマニア全土'}},
        regions={}, region_fill={}, admin1_word='県', city_strip=None, notes=[],
        src13='国境・海岸線・41県とブカレスト・' + CITYN('ルーマニア', 41), fig='東経20.243〜29.700度・北緯43.650〜48.275度'),
    'BGR': dict(W34, dir=os.path.join(DATA, 'BGR'), name='ブルガリア', geofabrik='europe/bulgaria-latest.osm.pbf', phi0=42.77,
        description=D34('ブルガリア'),
        terms='<b>区分の呼び名</b>：28の区分は <b>Oblast</b>（オブラスト）。', terms_reading=True,
        panels={'main': {'lon': (22.345, 28.604), 'lat': (41.238, 44.228), 'title': 'ブルガリア全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None, notes=[],
        src13='国境・海岸線・28州・' + CITYN('ブルガリア', 18), fig='東経22.345〜28.604度・北緯41.238〜44.228度'),
    'BLR': dict(W34, dir=os.path.join(DATA, 'BLR'), name='ベラルーシ', geofabrik='europe/belarus-latest.osm.pbf', phi0=53.52,
        description=D34('ベラルーシ'),
        terms='<b>区分の呼び名</b>：6の区分は <b>Voblasts</b>（ヴォブラスツ）、首都ミンスクは別の区分（Natural Earth では Gorod）。', terms_reading=True,
        panels={'main': {'lon': (23.166, 32.72), 'lat': (51.235, 56.157), 'title': 'ベラルーシ全土'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None,
        notes=[MOFA_NOT_CHECKED('ベラルーシ')],
        src13='国境・6州とミンスク・' + CITYN('ベラルーシ', 15), fig='東経23.166〜32.720度・北緯51.235〜56.157度'),
    'MDA': dict(W34, dir=os.path.join(DATA, 'MDA'), name='モルドバ', geofabrik='europe/moldova-latest.osm.pbf', phi0=47.19,
        description=D34('モルドバ'),
        terms=None, admin1_off=True,
        panels={'main': {'lon': (26.618, 30.132), 'lat': (45.462, 48.486), 'title': 'モルドバ全土'}},
        regions={}, region_fill={}, admin1_word='区分', city_strip=None,
        notes=['東の、ドニエストル川の左岸の細長い地域（<b>沿ドニエストル</b>）は、Natural Earth の国の形ではモルドバに入っていて、この図にも入っている。統治しているのは現地の当局で、モルドバの政府は治めていない（3-4 §06）。層2もこの地域の中を数えている。',
               'Natural Earth の区分（40）は使っていない（層3の区分名は「なし」と出る）。沿ドニエストルの中の区分の1つが「Rezina（レジナ）」という名前で入っているが、実際はルィブニツァ地区で（OpenStreetMap の境界と98%が重なる）、本物のレジナ地区は別にもう1つある。名前が実際と合わず、原語に切り替えても直らないため。',
               MOFA_NOT_CHECKED('モルドバ')],
        src13=CITYN('モルドバ', 5) + '。区分は使っていない（上の注記）', fig='東経26.618〜30.132度・北緯45.462〜48.486度'),
    'UKR': dict(W34, dir=os.path.join(DATA, 'UKR'), name='ウクライナ', geofabrik='europe/ukraine-latest.osm.pbf', phi0=49.20,
        description=D34('ウクライナ'),
        terms='<b>区分の呼び名</b>：24の区分は <b>Oblast</b>（オブラスト）、首都キーウは別の区分（Natural Earth では Rada）。', terms_reading=True,
        ja_replace={'キエフ': 'キーウ'},
        panels={'main': {'lon': (22.133, 40.16), 'lat': (44.3, 52.369), 'title': 'ウクライナ（Natural Earth の形）'}},
        regions={}, region_fill={}, admin1_word='州', city_strip=None,
        notes=['<b>クリミア半島は、Natural Earth ではロシアの形に入っていて、この国の形には入っていない</b>（図では隣の国と同じ薄い灰色）。層2もクリミアの中は数えていない。区分（25）にもクリミアとセヴァストポリは入っていない（3-4 §06）。',
               'ウクライナの東部・南部で、2022年以降ロシア側が支配している地域も、Natural Earth のとおりこの国の中に描いている。Natural Earth の描き方は、いまの実効支配と合っていない。前線が動いている地域は描き直さない（3-4 §06）。',
               '<b>首都は、Natural Earth の日本語名（キエフ）ではなく、外務省が2022年3月31日に変更した表記（キーウ）を使っている</b>（「ウクライナの首都等の呼称の変更」）。都市名と、区分の2つ（Natural Earth ではどちらも「キエフ」。州と市を分ける語は付いていない）を「キーウ」にした。発表には首都以外の地名の一覧が無いので、ほかの地名は Natural Earth の日本語名のままで、外務省の表記と合っているかは確かめていない。'],
        src13='国境・海岸線・25の区分（クリミアとセヴァストポリを除く）・' + CITYN('ウクライナ', 49), fig='東経22.133〜40.160度・北緯44.3〜52.369度'),
})
